import Head from 'next/head'
import Image from 'next/image'
import PolygonRenderer from "@/components/PolygonRenderer";
import { useState, useEffect, useRef } from 'react';
import useSound from 'use-sound';
import React from 'react';
import styles from '@/styles/Home.module.css'

export default function Home() {
  const [play, { stop, pause }] = useSound("/warning.mp3");
  const [data, setData] = useState([]);
  const [showImage_1, setShowImage_1] = useState(true);
  const [showImage_2, setShowImage_2] = useState(true);
  const [showImage_3, setShowImage_3] = useState(true);
  const [showImage_4, setShowImage_4] = useState(true);
  const fetchData = async () => {
    const res = await fetch(`/api/data`);
    const newData = await res.json();
    setData(newData);
   
  };

  useEffect(() => {
    fetchData();
    const intervalId = setInterval(fetchData, 10000); // 5秒ごとにデータを取得

    return () => {
      clearInterval(intervalId);
    };
  }, []);
  


  const geojson = {
    type: "FeatureCollection",
    features: [
      {
        type: "Feature",
        properties: {
          _color: "#000000",
          _opacity: 0.5,
          _weight: 3,
          _fillColor: "#ff0000",
          _fillOpacity: 0.5,
        },
        geometry: {
          type: "Polygon",
          coordinates: [
            [
              [0, 0],
              [0, 10],
              [10, 10],
              [10, 0],
              [0, 0],
            ],
          ],
        },
      },
    ],
  };

  return (
    <>    
    <Head>
    <title>カラス！</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
  <main >
  <div className={styles.description}>
          <p>
            カラスマップ&nbsp;
          </p>
  </div>
    <div>
        <div className={styles.map}>
          
          <Image
            src="/map.svg"
            width={3600}
            height={1200}
          />
        </div>
  

        <div className={showImage_1 ? styles.show_image_crow_1 : styles.hide_image_crow}>
          <Image
            src="/camera.svg"
            width={100}
            height={200}
          />
        </div> 
        <div className={showImage_2 ? styles.show_image_crow_2 : styles.hide_image_crow}>
          <Image
            src="/camera.svg"
            width={100}
            height={200}
          />
        </div>  
        <div className={showImage_3 ? styles.show_image_crow_3 : styles.hide_image_crow} >
          <Image
            src="/camera.svg"
            width={100}
            height={200}
          />
        </div>  
        <div className={showImage_4 ? styles.show_image_crow_4 : styles.hide_image_crow} >
          <Image
            src="/camera.svg"
            width={100}
            height={200}
          />
        </div>
        
        <div className={showImage_1 ? styles.show_image_crow_1 : styles.hide_image_crow}>
          <Image
            src="/crow.svg"
            width={200}
            height={400}
          />
        </div> 
        <div className={showImage_2 ? styles.show_image_crow_2 : styles.hide_image_crow}>
          <Image
            src="/crow.svg"
            width={200}
            height={400}
          />
        </div>  
        <div className={showImage_3 ? styles.show_image_crow_3 : styles.hide_image_crow} >
          <Image
            src="/crow.svg"
            width={200}
            height={400}
          />
        </div>  
        <div className={showImage_4 ? styles.show_image_crow_4 : styles.hide_image_crow} >
          <Image
            src="/crow.svg"
            width={200}
            height={400}
          />
        </div> 
 
    
     
        
      <PolygonRenderer geoJson={geojson} scale={10} />
      {data.map((item, i) => (
        <div key={i}>
        </div>
      ))}
    </div>
    </main>
    </>
  );
}
