import Head from 'next/head'
import Image from 'next/image'
import PolygonRenderer from "@/components/PolygonRenderer";
import CrowRender from "@/components/CrowRender";
import { useState, useEffect, useRef } from 'react';
import useSound from 'use-sound';
import React from 'react';
import styles from '@/styles/Home.module.css'

export default function Home() {
  const [play, { stop, pause }] = useSound("/warning.mp3");
  const [data, setData] = useState([]);
  const fetchData = async () => {
    const res = await fetch(`/api/data`);
    const newData = await res.json();
    setData(newData);
   
  };

  useEffect(() => {
    fetchData();
    const intervalId = setInterval(fetchData, 10000); // 5秒ごとにデータを取得

    return () => {
      clearInterval(intervalId);
    };
  }, []);
  


  const geojson = {
    type: "FeatureCollection",
    features: [
      {
        type: "Feature",
        properties: {
          _color: "#000000",
          _opacity: 0.5,
          _weight: 3,
          _fillColor: "#ff0000",
          _fillOpacity: 0.5,
        },
        geometry: {
          type: "Polygon",
          coordinates: [
            [
              [0, 0],
              [0, 10],
              [10, 10],
              [10, 0],
              [0, 0],
            ],
          ],
        },
      },
    ],
  };

  const crow_state = {
    pos1 : false,
    pos2 : false,
    pos3 : false,
    pos4 : false,
  }

  return (
    <>    
    <Head>
    <title>カラス！</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
  <div className={styles.description}>
          <p>
            カラスマップ&nbsp;
          </p>
  </div>
  
    
  <PolygonRenderer geoJson={geojson} scale={10} />  
  <CrowRender crow_state={crow_state} />    

      {data.map((item, i) => (
        <div key={i}>
        </div>
      ))}

    </>
  );
}
